// Copyright 2012 Google Inc. All rights reserved.
// Container Version: 36
(function(w,g){w[g]=w[g]||{};w[g].e=function(s){return eval(s);};})(window,'google_tag_manager');(function(){


var __e;(function(){(function(a){__e=a;__e.a="e";__e.b=["google"];__e.c=!0})(function(){return oa})})();

var __ua;(function(){var a;(function(a){__ua=a;__ua.a="ua";__ua.b=["google"];__ua.c=!0})(function(b){var c={},d={},e={},f={},g={};if(b[""]){var h=b[""];va(T(h["21"],"fieldName","value"),d);va(T(h[""],"index","group"),e);va(T(h["12"],"index","dimension"),f);va(T(h[""],"index","metric"),g);b[""]=null;h["21"]=void 0;h[""]=
void 0;h["12"]=void 0;h[""]=void 0;var k=wa(h,void 0);b=wa(b,k)}va(T(b["21"],"fieldName","value"),d);va(T(b[""],"index","group"),e);va(T(b["12"],"index","dimension"),f);va(T(b[""],"index","metric"),g);p("GoogleAnalyticsObject",b[""]||"ga",!0);var l=function(){return p("GoogleAnalyticsObject")},m=p(l(),function(){var a=p(l());a.q=a.q||[];a.q.push(arguments)},
!0);m.l=Number(new Date);var n="",q="";b["24"]&&"string"==typeof b[""]?""!==b[""]&&(q=b[""],n=q+"."):(q=xa(),n=q+".");var v={name:!0,clientId:!0,sampleRate:!0,siteSpeedSampleRate:!0,alwaysSendReferrer:!0,allowAnchor:!0,allowLinker:!0,cookieName:!0,cookieDomain:!0,cookieExpires:!0,cookiePath:!0,cookieUpdate:!0,legacyCookieDomain:!0,legacyHistoryImport:!0,storage:!0,useAmpClientId:!0,storeGac:!0},w={allowAnchor:!0,
allowLinker:!0,alwaysSendReferrer:!0,anonymizeIp:!0,cookieUpdate:!0,exFatal:!0,forceSSL:!0,javaEnabled:!0,legacyHistoryImport:!0,nonInteraction:!0,useAmpClientId:!0,useBeacon:!0,storeGac:!0},r=function(a){var b=[].slice.call(arguments,0);b[0]=n+b[0];p(l()).apply(window,b)},A=function(a,b){return void 0===b?b:a(b)},D=function(a,b){if(b)for(var c in b)b.hasOwnProperty(c)&&r("set",a+c,b[c])},x=function(){},z=function(a,b,c){var d=0;if(a)for(var e in a)if(a.hasOwnProperty(e)&&(c&&v[e]||!c&&void 0===v[e])){var f=w[e]?Aa(a[e]):a[e];"anonymizeIp"!=e||f||(f=void 0);b[e]=f;d++}return d},H={name:q};z(d,H,!0);m("create",b["27"]||
c.trackingId,H);r("set","&gtm","GTM-NZHN7H");(function(a,c){void 0!==b[c]&&r("set",a,b[c])})("nonInteraction","22");D("contentGroup",e);D("dimension",f);D("metric",g);var P={};z(d,P,!1)&&r("set",P);var E;b["16"]&&r("require","linkid","linkid.js");r("set","hitCallback",function(){var a=
d&&d.hitCallback;U(a)&&a();b["30"]()});if("TRACK_EVENT"==b["25"]){b["14"]&&(r("require","ec","ec.js"),x());var C={hitType:"event",eventCategory:String(b["20"]||c.category),eventAction:String(b["19"]||c.action),eventLabel:A(String,b[""]||c.label),eventValue:A(Ba,b[""]||c.value)};
z(E,C,!1);r("send",C);}else if("TRACK_SOCIAL"==b["25"]){}else if("TRACK_TRANSACTION"==
b["25"]){}else if("TRACK_TIMING"==b["25"]){}else if("DECORATE_LINK"==b["25"]){}else if("DECORATE_FORM"==
b["25"]){}else if("TRACK_DATA"==b["25"]){}else{b["14"]&&(r("require","ec","ec.js"),x());if(b["13"]||"DISPLAY_FEATURES"==b[""]){var N="_dc_gtm_"+String(b["27"]).replace(/[^A-Za-z0-9-]/g,"");r("require","displayfeatures",void 0,{cookieName:N})}"DISPLAY_FEATURES_WITH_REMARKETING_LISTS"==b[""]&&(N="_dc_gtm_"+String(b["27"]).replace(/[^A-Za-z0-9-]/g,
""),r("require","adfeatures",{cookieName:N}));E?r("send","pageview",E):r("send","pageview");}if(!a){var ja=b["28"]?
"u/analytics_debug.js":"analytics.js";b[""]&&!b["28"]&&(ja="internal/"+ja);a=!0;Da(y("https:","http:","//www.google-analytics.com/"+ja,d&&d.forceSSL),function(){p(l()).loaded||b["31"]();},b["31"])}})})();







var Bb=this;/*
 jQuery v1.9.1 (c) 2005, 2012 jQuery Foundation, Inc. jquery.org/license. */
var Cb=/\[object (Boolean|Number|String|Function|Array|Date|RegExp)\]/,Db=function(a){if(null==a)return String(a);var b=Cb.exec(Object.prototype.toString.call(Object(a)));return b?b[1].toLowerCase():"object"},Eb=function(a,b){return Object.prototype.hasOwnProperty.call(Object(a),b)},ya=function(a){if(!a||"object"!=Db(a)||a.nodeType||a==a.window)return!1;try{if(a.constructor&&!Eb(a,"constructor")&&!Eb(a.constructor.prototype,"isPrototypeOf"))return!1}catch(c){return!1}for(var b in a);return void 0===
b||Eb(a,b)},wa=function(a,b){var c=b||("array"==Db(a)?[]:{}),d;for(d in a)if(Eb(a,d)){var e=a[d];"array"==Db(e)?("array"!=Db(c[d])&&(c[d]=[]),c[d]=wa(e,c[d])):ya(e)?(ya(c[d])||(c[d]={}),c[d]=wa(e,c[d])):c[d]=e}return c};var db=null,Fb=Math.random(),Gb=null,oa=null,Ka=!1,Hb={},Ib={},La={};var Ma,Na,Jb,Kb,Lb,Mb,Nb,Ob,Pb,Qb,Rb,Sb,Tb,Ub,Vb,Wb,Xb,Yb,Zb,$b,ac,bc,cc,dc,ec,fc,gc,hc,ic,jc,kc,lc,mc,nc,oc,pc,qc,rc,sc,tc,uc,vc,wc,xc,yc,zc,Ac,Bc,Cc,Dc,Ec,Fc,Gc,Hc,Ic,Jc,Kc,Lc,Mc,Nc,Oc,Pc,Qc,Rc,Sc,Tc,Uc,Vc,Wc,Xc,Yc,Zc,$c,ad,bd,cd,dd,ed,fd,gd,hd,id,jd,kd,ld,md,nd,od,pd,qd,rd,sd,td,vd,wd,xd,yd,zd,Ad,Bd,Cd,Dd,Ed,Fd,Gd,Hd,Id,Jd,Kd,Ld,Md,Nd,Od,Pd,Qd,Rd,Sd,Td,Ud,Vd,Wd,Xd,Yd,Zd,$d,ae,be,ce,de,ee,fe,ge,he,ie,je,ke,le,me,ne,oe,pe,qe,re,se,te,ue,ve,we,xe,ye,ze,Ae,Be,Ce,De,Ee,Fe,Ge,He,Ie,Je,Ke,Le,Me,Ne,Oe,
Pe,Qe,Re,Se,Te,Ue,Ve,We,Xe,Ye,Ze,$e,af,bf,cf,df,ef,ff,gf,hf,jf,kf,lf,mf,nf,of,pf,qf,rf,sf,tf,uf,vf,wf,xf,yf,zf,Af,Bf,Cf,Df,Ef,Ff,Gf;
(function(){var a=function(a){return{toString:function(){return a}}};Jb=a("");Kb=a("");Lb="";Mb=a("");Nb=a("");Ob=a("");Pb=a("");Qb=a("");Rb=a("");Sb=a("");Tb=a("");Ub=a("0");Vb=a("1");Wb=a("");Xb=a("");Yb=a("");
Zb=a("");$b=a("");ac=a("");bc=a("");cc=a("");dc=a("");ec=a("");fc=a("");gc=a("");hc=a("");ic=a("");jc=a("");kc=a("");lc=a("");
mc=a("");nc=a("");oc=a("");pc=a("");qc=a("");rc=a("");sc=a("2");tc=a("");uc=a("");vc=a("");wc=a("");xc=a("");yc=a("");zc=a("");Ac=a("");Bc=a("");Cc=a("");
Dc=a("");Ec=a("");Fc=a("");Gc=a("");Hc=a("");Ic=a("");Jc=a("");Kc=a("");Lc=a("");Mc=a("");Nc=a("");Oc=a("");Pc=a("");Qc=a("");Rc=a("");Sc=a("");Tc=a("");
Uc=a("");Vc=a("");Wc=a("");Xc=a("");Yc=a("");Zc=a("");$c=a("");ad=a("");bd=a("");cd=a("");dd=a("");ed=a("");fd=a("");gd=a("");hd=a("");id=a("");
jd=a("");kd=a("");ld=a("");md=a("");nd=a("");od=a("");pd=a("");qd=a("");rd=a("");sd=a("");td=a("");Ma=a("3");vd=a("");wd=a("30");xd=a("31");yd=a("");zd=a("");
Ad=a("");Bd=a("");Cd=a("");Dd=a("");Ed=a("");Fd=a("");Na=a("4");Gd=a("");Hd=a("");Id=a("5");Jd=a("");Kd=a("");Ld=a("");Md=a("");Nd=a("");Od=a("");Pd=a("");Qd=a("");Rd=a("");Sd=a("");
Td=a("");Ud=a("");Vd=a("");Wd=a("");Xd=a("");Yd=a("");Zd=a("");$d=a("");ae=a("6");be=a("");ce=a("");de=a("");ee=a("");fe=a("");ge=a("");he=a("8");ie=a("");je=a("");ke=a("");le=a("");
me=a("");ne=a("");oe=a("");pe=a("");qe=a("");re=a("");se=a("");te=a("");ue=a("");ve=a("");we=a("");xe=a("");ye=a("");ze=a("");Ae=a("");Be=a("");Ce=a("");De=a("");Ee=a("");
Fe=a("");Ge=a("");He=a("");Ie=a("");Je=a("");Ke=a("");Le=a("");Me=a("");Ne=a("");Oe=a("");Pe=a("");Qe=a("");Re=a("");Se=a("");Te=a("9");Ue=
a("");Ve=a("");We=a("");Xe=a("");Ye=a("");Ze=a("");$e=a("");af=a("");bf=a("");cf=a("");df=a("");ef=a("");ff=a("");gf=a("");hf=a("");jf=a("");kf=a("");
lf=a("");mf=a("");nf=a("");of=a("");pf=a("");qf="";rf=a("");sf=a("");tf=a("");uf=a("");vf=a("");wf=a("");xf=a("");yf=a("");zf=a("");Af=a("");Bf=a("");Cf=
a("");Df=a("");Ef=a("");Ff=a("");Gf=a("")})();var Ab=function(a,b){wa(a,b)},ob=function(){},U=function(a){return"function"==typeof a},Qa=function(a){return"[object Array]"==Object.prototype.toString.call(Object(a))},Hf=function(a){return"number"==Db(a)&&!isNaN(a)},If=function(a){return/^[0-9]+$/.test(a)},sb=function(a){return"string"==Db(a)},tb=function(a,b){if(Array.prototype.indexOf){var c=a.indexOf(b);return"number"==typeof c?c:-1}for(var d=0;d<a.length;d++)if(a[d]===b)return d;return-1},na=function(a){return a?a.replace(/^\s+|\s+$/g,""):
""},W=function(a){return Math.round(Number(a))||0},Aa=function(a){return"false"==String(a).toLowerCase()?!1:!!a},Mf=function(a){var b=[];if(Qa(a))for(var c=0;c<a.length;c++)b.push(String(a[c]));return b},O=function(){return new Date},ta=function(a,b){if(!Hf(a)||!Hf(b)||a>b)a=0,b=2147483647;return Math.floor(Math.random()*(b-a+1)+a)},Nf=function(){this.prefix="gtm.";this.values={}};Nf.prototype.set=function(a,b){this.values[this.prefix+a]=b};
Nf.prototype.get=function(a){return this.values[this.prefix+a]};Nf.prototype.contains=function(a){return void 0!==this.get(a)};
var Of=function(a,b,c){try{if(!a[Vd])return a[Ma](a,b||ob,c||ob);c&&c()}catch(d){}return!1},Pf=function(a,b){function c(b,c){a.contains(b)||a.set(b,[]);a.get(b).push(c)}for(var d=na(b).split("&"),e=0;e<d.length;e++)if(d[e]){var f=d[e].indexOf("=");0>f?c(d[e],"1"):c(d[e].substring(0,f),d[e].substring(f+1))}},Qf=function(a){var b=a?a.length:0;return 0<b?a[b-1]:""},Rf=function(a){return function(){return a("GTM-NZHN7H")}},Sf=function(a){for(var b=0;b<a.length;b++)a[b]()},xa=function(){return"gtm"+Tf()},
Tf=function(){var a=db.sequence||0;db.sequence=a+1;return a},za=function(a,b,c){return a&&a.hasOwnProperty(b)?a[b]:c},Uf=function(a){return null!==a&&void 0!==a&&void 0!==a.length},Vf=function(a,b){0==b?a.Eb=!0:a.fa=!0;var c=a.h;a.B&&(a.B.bb[c]=b);Hb[c]&&(Hb[c].state=b)},Wf=function(a,b){a.sort(function(a,d){return b(a,d)?-1:b(d,a)?1:0})};var B=window,R=document,Yf=navigator,Ja=function(a,b){var c=B[a];B[a]=void 0===c?b:c;return B[a]},Q=function(a,b,c,d){return(d||"http:"!=B.location.protocol?a:b)+c},Zf=function(a){var b=R.getElementsByTagName("script")[0]||R.body||R.head;b.parentNode.insertBefore(a,b)},hb=function(a,b){b&&(a.addEventListener?a.onload=b:a.onreadystatechange=function(){a.readyState in{loaded:1,complete:1}&&(a.onreadystatechange=null,b())})},t=function(a,b,c){var d=R.createElement("script");d.type="text/javascript";
d.async=!0;d.src=a;hb(d,b);c&&(d.onerror=c);Zf(d);return d},ha=function(a,b){var c=R.createElement("iframe");c.height="0";c.width="0";c.style.display="none";c.style.visibility="hidden";Zf(c);hb(c,b);void 0!==a&&(c.src=a);return c},I=function(a,b,c){var d=new Image(1,1);d.onload=function(){d.onload=null;b&&b()};d.onerror=function(){d.onerror=null;c&&c()};d.src=a},S=function(a,b,c,d){a.addEventListener?a.addEventListener(b,c,!!d):a.attachEvent&&a.attachEvent("on"+b,c)},fa=function(a,b,c){a.removeEventListener?
a.removeEventListener(b,c,!1):a.detachEvent&&a.detachEvent("on"+b,c)},u=function(a){B.setTimeout(a,0)},jb=!1,lb=[],$f=function(a){if(!jb){var b=R.createEventObject,c="complete"==R.readyState,d="interactive"==R.readyState;if(!a||"readystatechange"!=a.type||c||!b&&d){jb=!0;for(var e=0;e<lb.length;e++)u(lb[e])}lb.push=function(){for(var a=0;a<arguments.length;a++)u(arguments[a]);return 0}}},ag=0,bg=function(){if(!jb&&140>ag){ag++;try{R.documentElement.doScroll("left"),$f()}catch(a){B.setTimeout(bg,50)}}},
ka=function(a){var b=R.getElementById(a);if(b&&la(b,"id")!=a)for(var c=1;c<document.all[a].length;c++)if(la(document.all[a][c],"id")==a)return document.all[a][c];return b},la=function(a,b){return a&&b&&a.attributes&&a.attributes[b]?a.attributes[b].value:null},$a=function(a){return a.target||a.srcElement||{}},ma=function(a){var b=a.innerText||a.textContent||"";b&&" "!=b&&(b=b.replace(/^[\s\xa0]+|[\s\xa0]+$/g,""));b&&(b=b.replace(/(\xa0+|\s{2,}|\n|\r\t)/g," "));return b},rb=function(a){var b=R.createElement("div");
b.innerHTML="A<div>"+a+"</div>";b=b.lastChild;for(var c=[];b.firstChild;)c.push(b.removeChild(b.firstChild));return c},ab=function(a,b){for(var c={},d=0;d<b.length;d++)c[b[d]]=!0;var e=a;for(d=0;e&&!c[String(e.tagName).toLowerCase()]&&100>d;d++)e=e.parentElement;e&&!c[String(e.tagName).toLowerCase()]&&(e=null);return e},cg=!1,dg=[],eg=function(){if(!cg){cg=!0;for(var a=0;a<dg.length;a++)u(dg[a])}},fg=function(a){a=a||B;var b=a.location.href,c=b.indexOf("#");return 0>c?"":b.substring(c+1)},pb=function(a){window.console&&
window.console.log&&window.console.log(a)};var ra=function(a,b,c,d,e){var f,g=(a.protocol.replace(":","")||B.location.protocol.replace(":","")).toLowerCase();b&&(b=String(b).toLowerCase());switch(b){case "protocol":f=g;break;case "host":f=(a.hostname||B.location.hostname).split(":")[0].toLowerCase();if(c){var h=/^www\d*\./.exec(f);h&&h[0]&&(f=f.substr(h[0].length))}break;case "port":f=String(1*(a.hostname?a.port:B.location.port)||("http"==g?80:"https"==g?443:""));break;case "path":f="/"==a.pathname.substr(0,1)?a.pathname:"/"+a.pathname;var k=
f.split("/");0<=tb(d||[],k[k.length-1])&&(k[k.length-1]="");f=k.join("/");break;case "query":f=a.search.replace("?","");if(e)a:{for(var l=f.split("&"),m=0;m<l.length;m++){var n=l[m].split("=");if(decodeURIComponent(n[0]).replace(/\+/g," ")==e){f=decodeURIComponent(n.slice(1).join("=")).replace(/\+/g," ");break a}}f=void 0}break;case "fragment":f=a.hash.replace("#","");break;default:f=a&&a.href}return f},qa=function(a){var b="";if(a&&a.href){var c=a.href.indexOf("#");b=0>c?a.href:a.href.substr(0,c)}return b},
pa=function(a){var b=R.createElement("a");a&&(b.href=a);return b};var Ca=function(a,b){var c=function(){};c.prototype=a.prototype;var d=new c;a.apply(d,Array.prototype.slice.call(arguments,1));return d};var ca=function(a){var b=["veinteractive.com","ve-interactive.cn"];if(!a)return!1;var c=ra(pa(a),"host");if(!c)return!1;for(var d=0;b&&d<b.length;d++){var e=b[d]&&b[d].toLowerCase();if(e){var f=c.length-e.length;0<f&&"."!=e.charAt(0)&&(f--,e="."+e);if(0<=f&&c.indexOf(e,f)==f)return!0}}return!1};
var T=function(a,b,c){for(var d={},e=!1,f=0;a&&f<a.length;f++)a[f]&&a[f].hasOwnProperty(b)&&a[f].hasOwnProperty(c)&&(d[a[f][b]]=a[f][c],e=!0);return e?d:null},fb=function(a,b){for(var c=[],d=0;a&&d<a.length;d++)a[d]&&a[d].hasOwnProperty(b)&&c.push(a[d][b]);return c},va=function(a,b){wa(a,b)},Ba=function(a){return W(a)};var gg={event:function(a){var b=a[1];if(sb(b)&&!(3<a.length)){var c;if(2<a.length){if(!ya(a[2]))return;c=a[2]}var d=c,e={event:b};d&&(d=wa(d,void 0),e.eventModel=d,e.eventCallback=d.eventCallback);return e}},set:function(a){var b;2==a.length&&ya(a[1])?b=wa(a[1],void 0):3==a.length&&sb(a[1])&&(b={},b[a[1]]=a[2]);if(b)return b._clear=!0,b},js:function(a){if(2==a.length&&a[1].getTime)return{event:"gtm.js","gtm.start":a[1].getTime()}}};var hg=new Nf,ig={},kg={set:function(a,b){wa(jg(a,b),ig)},get:function(a){return Y(a,2)},reset:function(){hg=new Nf;ig={}}},Y=function(a,b){var c;if(2!=b)c=hg.get(a);else a:{for(var d=a.split("."),e=0,f=ig.eventModel;void 0!==f&&e<d.length;e++)f=f[d[e]];if(void 0!==f||1<e)c=f;else{var g=ig;for(e=0;e<d.length;e++){if(void 0===g[d[e]]){c=void 0;break a}g=g[d[e]]}c=g}}return c},lg=function(a,b){hg.set(a,b);wa(jg(a,b),ig)},jg=function(a,b){for(var c={},d=c,e=a.split("."),f=0;f<e.length-1;f++)d=d[e[f]]=
{};d[e[e.length-1]]=b;return c};var mg=!1,ng=!1;var og=Math.random(),pg="0.050000">og;
var qg=function(a,b){if(pg){var c="//www.googletagmanager.com/a?id=GTM-NZHN7H&cv=36",d=function(a,b){b&&(c+=a+encodeURIComponent(b))};d("&v=","t");d("&n=",a);d("&s=",b&&b.state);d("&h=",b&&b.hideLatency);d("&g=",b&&b.gaLatency);d("&p=",b&&b.loadBy);d("&o=",b&&b.timeout);d("&l=",O().getTime()-W(Gb));c+="&sr=0.050000";d("&ps=",og);d("&cb=",ta());I(c)}},rg=ob,sg=function(){var a=!1;};var ug=function(a){var b=db.zones;return b?b.checkState("GTM-NZHN7H",a):tg},tg={active:!0,isWhitelisted:function(){return!0}};var wg=ob,xg=[],yg=!1,ea=function(a){return B["dataLayer"].push(a)},zg=function(a){var b=!1;return function(){!b&&U(a)&&u(Rf(a));b=!0}},Ig=function(){for(var a=!1;!yg&&0<xg.length;){yg=!0;delete ig.eventModel;var b=xg.shift();if(U(b))try{b.call(kg)}catch(kb){}else if(Qa(b))a:{var c=b;if(sb(c[0])){for(var d=c[0].split("."),e=d.pop(),f=c.slice(1),g=ig,h=0;h<d.length;h++){if(void 0===g[d[h]])break a;g=g[d[h]]}try{g[e].apply(g,f)}catch(kb){}}}else{var k=b;if(k&&("[object Arguments]"==Object.prototype.toString.call(k)||
Object.prototype.hasOwnProperty.call(k,"callee"))){a:{var l=b;if(l.length&&sb(l[0])){var m=gg[l[0]];if(m){b=m(l);break a}}b=void 0}if(!b){yg=!1;continue}}var n=void 0,q=void 0,v=b,w=v._clear;for(q in v)v.hasOwnProperty(q)&&"_clear"!==q&&(w&&lg(q,void 0),lg(q,v[q]));var r=!1,A=v.event;if(A){v.hasOwnProperty("gtm.uniqueEventId")||(v["gtm.uniqueEventId"]=Tf(),lg("gtm.uniqueEventId",v["gtm.uniqueEventId"]));n=v["gtm.uniqueEventId"];oa=A;var D=ug(n);if(D.active){var x=zg(v.eventCallback),z=v.eventTimeout;
z&&B.setTimeout(x,Number(z));r=wg(n,A,D.isWhitelisted,x,v.eventReporter)}}Gb||(Gb=v["gtm.start"])&&rg();var H,P=v,E=n,C=A,F=ig;oa=null;a=r||a}yg=!1}return!a},Jg=function(){var a=Ig();try{var b=B["dataLayer"].hide;if(b&&void 0!==b["GTM-NZHN7H"]&&b.end){b["GTM-NZHN7H"]=!1;var c=!0,d;for(d in b)if(b.hasOwnProperty(d)&&!0===b[d]){c=!1;break}c&&(b.end(),b.end=null)}}catch(e){}return a},Kg=function(){var a=Ja("dataLayer",[]),b=Ja("google_tag_manager",{});b=b["dataLayer"]=b["dataLayer"]||{};lb.push(function(){b.gtmDom||(b.gtmDom=!0,a.push({event:"gtm.dom"}))});
dg.push(function(){b.gtmLoad||(b.gtmLoad=!0,a.push({event:"gtm.load"}))});var c=a.push;a.push=function(){var b=[].slice.call(arguments,0);c.apply(a,b);for(xg.push.apply(xg,b);300<this.length;)this.shift();return Ig()};xg.push.apply(xg,a.slice(0));u(Jg)};var Ra,Lg,Mg,Xa=/(Firefox\D28\D)/g.test(Yf.userAgent),Og=function(a,b){return function(c){c=c||B.event;var d=$a(c),e=!1;if(3!==c.which||"LINK_CLICK"!=a){"LINK_CLICK"==a&&(d=ab(d,["a","area"]),e=!d||!d.href||Ng(d.href)||2===c.which||null==c.which&&4==c.button||c.ctrlKey||c.shiftKey||c.altKey||!0===c.metaKey);var f="FORM_SUBMIT"==a?Ra:Mg;if(c.defaultPrevented||!1===c.returnValue||c.ka&&c.ka()){if(d){var g={simulateDefault:!1},h=Sa(f,["wnc","nwnc"]);h&&Ta(a,d,g,f.wt,h)}}else{if(d){g={};var k,l=Sa(f,
["wnc","nwnc","nwc","wc"]);(k=Ta(a,d,g,f.wt,l))||(Ua(g.eventReport,f)?b=!0:e=!0);e=e||k||"LINK_CLICK"==a&&Xa;g.simulateDefault=!k&&b&&!e;g.simulateDefault&&(e=Ya(d,g)||e,!e&&c.preventDefault&&c.preventDefault());c.returnValue=k||!b||e;return c.returnValue}return!0}}}},Ta=function(a,b,c,d,e){var f=d||2E3,g=vb(b,a);switch(a){case "LINK_CLICK":g["gtm.triggers"]=e||"";g.event="gtm.linkClick";g.eventTimeout=f;g.eventCallback=Pg(b,c);g.eventReporter=function(a){c.eventReport=a};break;case "FORM_SUBMIT":g["gtm.triggers"]=
e||"";g.event="gtm.formSubmit";g.eventTimeout=f;g.eventCallback=Qg(b,c);g.eventReporter=function(a){c.eventReport=a};break;case "CLICK":g.event="gtm.click";break;default:return!0}return ea(g)},Wa=function(a){var b=a.target;if(!b)switch(String(a.tagName).toLowerCase()){case "a":case "area":case "form":b="_self"}return b},Ya=function(a,b){var c=!1,d=/(iPad|iPhone|iPod)/g.test(Yf.userAgent),e=Wa(a).toLowerCase();switch(e){case "":case "_self":case "_parent":case "_top":var f;f=(e||"_self").substring(1);
b.targetWindow=B.frames&&B.frames[f]||B[f];break;case "_blank":d?(b.simulateDefault=!1,c=!0):(b.targetWindowName="gtm_autoEvent_"+O().getTime(),b.targetWindow=B.open("",b.targetWindowName));break;default:d&&!B.frames[e]?(b.simulateDefault=!1,c=!0):(B.frames[e]||(b.targetWindowName=e),b.targetWindow=B.frames[e]||B.open("",e))}return c},Pg=function(a,b,c){return function(){b.simulateDefault&&(b.targetWindow?b.targetWindow.location.href=a.href:(c=c||O().getTime(),500>O().getTime()-c&&B.setTimeout(Pg(a,
b,c),25)))}},Qg=function(a,b,c){return function(){if(b.simulateDefault)if(b.targetWindow){var d;b.targetWindowName&&(d=a.target,a.target=b.targetWindowName);R.gtmSubmitFormNow=!0;Va(a).call(a);b.targetWindowName&&(a.target=d)}else c=c||O().getTime(),500>O().getTime()-c&&B.setTimeout(Qg(a,b,c),25)}},Sa=function(a,b){for(var c=[],d=0;d<b.length;d++){var e=a[b[d]],f;for(f in e)e.hasOwnProperty(f)&&e[f]&&c.push(f)}return c.join(",")},Rg=function(a,b,c,d,e){var f=e;if(!f||"0"==f){if(a.l)return;a.l=!0;
f="0"}var g=a.wt;b&&(!g||g>d)&&(a.wt=d);a[b?c?"wc":"wnc":c?"nwc":"nwnc"][f]=!0},Ua=function(a,b){if(b.wnc["0"]||b.wc["0"])return!0;for(var c=0;c<Sg.length;c++)if(a.passingRules[c]){var d=Tg[c],e=d&&d[0]&&d[0][0]||d[1]&&d[1][0];if(e&&"0"!=e&&(b.wc[e]||b.wnc[e]))for(var f=Sg[c][1],g=0;g<f.length;g++)if(a.resolvedTags[f[g]])return!0}return!1},sa=function(a,b,c,d,e){var f,g,h=!1;switch(a){case "CLICK":if(R.gtmHasClickListenerTag)return;R.gtmHasClickListenerTag=!0;f="click";g=function(a){var b=$a(a);b&&
Ta("CLICK",b,{},d)};h=!0;break;case "LINK_CLICK":b&&!Lg&&(Lg=qa(R.location));Rg(Mg,b||!1,c||!1,d,e);if(R.gtmHasLinkClickListenerTag)return;R.gtmHasLinkClickListenerTag=!0;f="click";g=Og(a,b||!1);break;case "FORM_SUBMIT":Rg(Ra,b||!1,c||!1,d,e);if(R.gtmHasFormSubmitListenerTag)return;R.gtmHasFormSubmitListenerTag=!0;f="submit";g=Og(a,b||!1);break;default:return}S(R,f,g,h)},Ng=function(a){if(!Lg)return!0;var b=a.indexOf("#");if(0>b)return!1;if(0==b)return!0;var c=pa(a);return Lg==qa(c)},Va=function(a){try{if(a.constructor&&
a.constructor.prototype)return a.constructor.prototype.submit}catch(b){}if(a.gtmReplacedFormSubmit)return a.gtmReplacedFormSubmit;R.gtmFormElementSubmitter||(R.gtmFormElementSubmitter=R.createElement("form"));return R.gtmFormElementSubmitter.submit.call?R.gtmFormElementSubmitter.submit:a.submit},vb=function(a,b){var c={"gtm.element":a,"gtm.elementClasses":a.className,"gtm.elementId":a["for"]||la(a,"id")||"","gtm.elementTarget":a.formTarget||a.target||""};switch(b){case "LINK_CLICK":c["gtm.elementUrl"]=
a.href;break;case "FORM_SUBMIT":var d=a.action;d&&d.tagName&&(d=a.cloneNode(!1).action);c["gtm.elementUrl"]=d;break;default:c["gtm.elementUrl"]=(a.attributes&&a.attributes.formaction?a.formAction:"")||a.action||a.href||a.src||a.code||a.codebase||""}return c},Ug=function(){var a=function(a){var b=Ja("google_tag_manager",{}),d=b[a];d||(d=b[a]={},d.nwnc={},d.nwc={},d.wnc={},d.wc={},d.wt=null,d.l=!1);return d};Mg=a("linkClickMap");Ra=a("formSubmitMap")};var ia=function(a){var b=R;return Vg?b.querySelectorAll(a):null},Wg=!1;if(R.querySelectorAll)try{var Xg=R.querySelectorAll(":root");Xg&&1==Xg.length&&Xg[0]==R.documentElement&&(Wg=!0)}catch(a){}var Vg=Wg;var Yg,Zg;
var dh=function(){};var Za=function(a,b,c){S(a,b,c,void 0)},ba=function(a,b,c){t(a,b,c)},Pa={},Da=function(a,b,c){var d=Pa[a];if(void 0===d){var e=function(a,b){return function(){a.status=b;for(var c=2==b?a.Fb:a.rb,d=0;d<c.length;d++)B.setTimeout(c[d],0)}};d={status:1,Fb:[],rb:[],Lc:void 0};d.rd=t(a,e(d,2),e(d,3));Pa[a]=d}0===d.status&&(d.Lc(),d.status=2);2===d.status?b&&b():3===d.status?c&&c():1===d.status&&(b&&d.Fb.push(b),c&&d.rb.push(c))},V=function(a,b){return Y(a,b||2)},aa=function(a,b){B[a]=b},p=function(a,b,
c){var d=B;b&&(void 0===d[a]||c&&!d[a])&&(d[a]=b);return d[a]},y=function(a,b,c,d){return(d||"http:"!=B.location.protocol?a:b)+c},xb=function(a){},Ia=function(a,b,c){},
zb=void 0,Ha=function(a){if(!zb){var b=function(){var a=R.body;if(a)if(p("MutationObserver"))(new MutationObserver(function(){for(var a=0;a<zb.length;a++)u(zb[a])})).observe(a,{childList:!0,subtree:!0});else{var b=!1;Za(a,"DOMNodeInserted",function(){b||(b=!0,u(function(){b=!1;for(var a=0;a<zb.length;a++)u(zb[a])}))})}};zb=[];R.body?b():u(b)}zb.push(a)};var gh=new RegExp(/^(.*\.)?(google|youtube|blogger|withgoogle)(\.com?)?(\.[a-z]{2})?\.?$/),hh={customPixels:["nonGooglePixels"],html:["customScripts","customPixels","nonGooglePixels","nonGoogleScripts","nonGoogleIframes"],customScripts:["html","customPixels","nonGooglePixels","nonGoogleScripts","nonGoogleIframes"],nonGooglePixels:[],nonGoogleScripts:["nonGooglePixels"],nonGoogleIframes:["nonGooglePixels"]},ih={customPixels:["customScripts","html"],html:["customScripts"],customScripts:["html"],nonGooglePixels:["customPixels",
"customScripts","html","nonGoogleScripts","nonGoogleIframes"],nonGoogleScripts:["customScripts","html"],nonGoogleIframes:["customScripts","html","nonGoogleScripts"]},jh=function(a,b){for(var c=[],d=0;d<a.length;d++)c.push(a[d]),c.push.apply(c,b[a[d]]||[]);return c},Bg=function(a){var b=Y("gtm.whitelist");
var c=b&&jh(Mf(b),hh),d=Y("gtm.blacklist")||Y("tagTypeBlacklist")||[];gh.test(B.location&&B.location.hostname)&&(d=Mf(d),d.push("nonGooglePixels","nonGoogleScripts"));var e=d&&jh(Mf(d),ih),f={};return function(g){var h=g&&g[Ma];if(!h)return!0;if(void 0!==f[h.a])return f[h.a];var k=a(h.a);if(b){var l;if(l=k)a:{if(0>tb(c,h.a))if(h.b&&0<h.b.length)for(var m=0;m<h.b.length;m++){if(0>
tb(c,h.b[m])){l=!1;break a}}else{l=!1;break a}l=!0}k=l}var n=!1;if(d){var q;if(!(q=0<=tb(e,h.a)))a:{for(var v=h.b||[],w=new Nf,r=0;r<e.length;r++)w.set(e[r],!0);for(r=0;r<v.length;r++)if(w.get(v[r])){q=!0;break a}q=!1}n=q}return f[h.a]=!k||n}};var _jsm=function(a){if(void 0!==a[Id])try{var b=B.google_tag_manager;return b&&b.e&&b.e(a[Id])}catch(c){}};_jsm.a="jsm";_jsm.b=["customScripts"];var kh=void 0,lh="",mh=0,nh=void 0,_et=function(a){var b,c=Y("gtm.element"),d=Y("event"),e=Number(O());kh===c&&lh===d&&mh>e-250?b=nh:(nh=b=c?ma(c):"",kh=c,lh=d);mh=e;return b?b:a[Sc]};_et.a="et";_et.b=["google"];var _eu=function(a){var b=String(Y("gtm.elementUrl")||a[Sc]||""),c=pa(b);return b};_eu.a="eu";_eu.b=["google"];var oh=/(^|\.)doubleclick\.net$/i,ph=/^(www\.)?google(\.com?)?(\.[a-z]{2})?$/,bb=function(a){for(var b=String(R.cookie).split(";"),c=[],d=0;d<b.length;d++){var e=b[d].split("="),f=na(e[0]);if(f&&f==a){var g=na(e.slice(1).join("="));g&&(g=decodeURIComponent(g));c.push(g)}}return c},qh=function(a,b,c,d,e){if(oh.test(R.location.hostname)||"/"==c&&ph.test(d))return!1;var f=a+"="+b+"; ";c&&(f+="path="+c+"; ");e&&(f+="expires="+e.toGMTString()+"; ");d&&(f+="domain="+d+";");var g=R.cookie;R.cookie=f;return g!=
R.cookie||0<=tb(bb(a),b)},rh=function(a){if("none"==a)return 0;0==a.indexOf(".")&&(a=a.substr(1));return a.split(".").length},sh=function(a){var b=a;b?(1<b.length&&b.lastIndexOf("/")==b.length-1&&(b=b.substr(0,b.length-1)),0!=b.indexOf("/")&&(b="/"+b),a=b):a="/";return"/"==a?1:a.split("/").length},th=function(){var a=ra(B.location,"host",!0).split(".");if(4==a.length&&/^[0-9]*$/.exec(a[3]))return["none"];for(var b=[],c=a.length-2;0<=c;c--)b.push(a.slice(c).join("."));b.push("none");return b};var uh=function(a,b){this.g=a;this.m=b};uh.prototype.toString=function(){var a=""+this.g;1<this.m&&(a=a+"-"+this.m);return a};var vh=function(a,b){this.$a=a;this.Aa=b};vh.prototype.toString=function(){return""+this.Aa+"."+this.$a};var yh=function(a,b){var c=new wh(null,a,b);xh(c);return c},wh=function(a,b,c){this.ob=Math.floor(O().getTime()/864E5);this.ya=b||"auto";this.na=c||"/";var d=rh(this.ya),e=sh(this.na);this.H=a||new uh(d,e);this.i=[];this.D=new Nf},Ah=function(a,b,c){b&&(""==c.$a?zh(a,b):(a.D.contains(b)||a.i.push(b),a.D.set(b,c)))},Bh=function(a,b){for(var c=0;c<b.length;c++)Ah(a,b[c][0],b[c][1])},zh=function(a,b){var c=tb(a.i,b);0<=c&&a.i.splice(c,1);a.D.set(b,void 0)},Ch=function(a){for(var b=[],c=0;c<a.i.length;c++){var d=
a.i[c];b.push([d,a.D.get(d)])}return b},Dh=function(a){for(var b=0,c=0;c<a.i.length;c++)b=Math.max(b,a.D.get(a.i[c]).Aa);return 864E5*b};wh.prototype.toString=function(){if(0==this.i.length)return"";for(var a=[],b=0;b<this.i.length;b++){var c=this.i[b];a.push(""+c+"."+this.D.get(c).toString())}return"GAX1."+this.H.toString()+"."+a.join("!")};
var Eh=function(a,b){for(var c=new Date,d=sh(a.na),e=[],f=0;f<a.i.length;f++){var g=a.i[f];a.D.get(g).Aa<a.ob&&e.push(g)}for(f=0;f<e.length;f++)zh(a,e[f]);if(a.i.length>(b||10))return!1;c.setTime(Dh(a));if("auto"!=a.ya)return qh("_gaexp",a.toString(),a.na,a.ya,c);for(var h=th(),k=0;k<h.length;k++)if("none"!=h[k]&&(a.H=new uh(rh(h[k]),d),qh("_gaexp",a.toString(),a.na,h[k],c)))return!0;return!1},xh=function(a){for(var b=a.H.g,c=a.H.m,d=bb("_gaexp"),e=[],f=0;f<d.length;f++){var g=Fh(a,d[f]);g&&e.push(g)}Wf(e,
function(a,d){var e=a.H,f=d.H;return e.g==f.g&&e.m==f.m?!1:e.g==b&&e.m==c?!0:f.g==b&&f.m==c?!1:e.g==b?f.g!=b||e.m<f.m:f.g==b?!1:e.m==c?f.g!=b&&(f.m!=c||e.g<f.g):f.m==c?!1:e.g<f.g||e.g==f.g&&e.m<f.m});a.H=0<e.length?e[0].H:new uh(b,c);for(f=e.length-1;0<=f;f--)Bh(a,Ch(e[f]))},Fh=function(a,b){var c=b.match(/GAX1\.([^.]+).(.*)/);if(c){var d;a:{var e=(c[1]||"").split("-");if(!(0==e.length||2<e.length)){var f=na(e[0]);if(0!=f.length){var g=2==e.length?na(e[1]):"1";if(If(f)&&If(g)){d=new uh(W(f),W(g));
break a}}}d=void 0}if(d){for(var h=new wh(d,a.ya,a.na),k=(c[2]||"").split("!"),l=0;l<k.length;l++){var m=k[l].split(".");if(3==m.length){if(!If(m[1]))return;Ah(h,m[0],new vh(m[2],W(m[1])))}}return h}}};var _v=function(a){var b=Y(a[ae].replace(/\\\./g,"."),a[Kc]);return void 0!==b?b:a[Sc]};_v.a="v";_v.b=["google"];var _f=function(a){var b=String(Y("gtm.referrer")||R.referrer);if(!b)return b;var c=pa(b);return b};_f.a="f";_f.b=["google"];var Jh=function(a){var b=B.location,c;(c=a[Hc]?a[Hc]:Y("gtm.url"))&&(b=pa(String(c)));var d=b.href,e=d.indexOf("#"),f=0>e?d:d.substr(0,e);a[sc]&&(f=ra(b,a[sc],a[Ne],a[Rc],a[Ae]));return f},_u=Jh;_u.a="u";_u.b=["google"];var _cn=function(a){return 0<=String(a[Ub]).indexOf(String(a[Vb]))};_cn.a="cn";_cn.b=["google"];var _eq=function(a){return String(a[Ub])==String(a[Vb])};_eq.a="eq";_eq.b=["google"];var _re=function(a){return(new RegExp(a[Vb],a[Cd]?"i":void 0)).test(a[Ub])};_re.a="re";_re.b=["google"];var cb=new String("undefined"),mb=function(a){this.resolve=function(b){for(var c=[],d=0;d<a.length;d++)c.push(a[d]===cb?b:a[d]);return c.join("")}};mb.prototype.toString=function(){return this.resolve("undefined")};mb.prototype.valueOf=mb.prototype.toString;var Th={},nb=function(a,b){var c=Tf();Th[c]=[a,b];return c},Uh=function(a){var b=a?0:1;return function(a){var c=Th[a];if(c&&U(c[b]))c[b]();Th[a]=void 0}};var Vh=String.prototype.trim?function(a){return a.trim()}:function(a){return a.replace(/^[\s\xa0]+|[\s\xa0]+$/g,"")},Wh=function(a,b){return a<b?-1:a>b?1:0};var Xh;a:{var Yh=Bb.navigator;if(Yh){var Zh=Yh.userAgent;if(Zh){Xh=Zh;break a}}Xh=""}var Z=function(a){return-1!=Xh.indexOf(a)};var $h=function(){return Z("iPhone")&&!Z("iPod")&&!Z("iPad")};var ai=function(a){ai[" "](a);return a};ai[" "]=function(){};var ci=function(a,b){var c=bi;return Object.prototype.hasOwnProperty.call(c,a)?c[a]:c[a]=b(a)};var di=Z("Opera"),ei=Z("Trident")||Z("MSIE"),fi=Z("Edge"),gi;if(gi=Z("Gecko")){var hi=Xh.toLowerCase();gi=!(-1!=hi.indexOf("webkit")&&!Z("Edge"))}var ii=gi&&!(Z("Trident")||Z("MSIE"))&&!Z("Edge"),ji=Xh.toLowerCase(),ki=-1!=ji.indexOf("webkit")&&!Z("Edge");ki&&Z("Mobile");Z("Macintosh");Z("Windows");Z("Linux")||Z("CrOS");var li=Bb.navigator||null;li&&(li.appVersion||"").indexOf("X11");Z("Android");$h();Z("iPad");Z("iPod");$h()||Z("iPad")||Z("iPod");
var mi=function(){var a=Bb.document;return a?a.documentMode:void 0},ni;a:{var oi="",pi=function(){var a=Xh;if(ii)return/rv\:([^\);]+)(\)|;)/.exec(a);if(fi)return/Edge\/([\d\.]+)/.exec(a);if(ei)return/\b(?:MSIE|rv)[: ]([^\);]+)(\)|;)/.exec(a);if(ki)return/WebKit\/(\S+)/.exec(a);if(di)return/(?:Version)[ \/]?(\S+)/.exec(a)}();pi&&(oi=pi?pi[1]:"");if(ei){var qi=mi();if(null!=qi&&qi>parseFloat(oi)){ni=String(qi);break a}}ni=oi}
var ri=ni,bi={},si=function(a){return ci(a,function(){for(var b=0,c=Vh(String(ri)).split("."),d=Vh(String(a)).split("."),e=Math.max(c.length,d.length),f=0;0==b&&f<e;f++){var g=c[f]||"",h=d[f]||"";do{var k=/(\d*)(\D*)(.*)/.exec(g)||["","","",""],l=/(\d*)(\D*)(.*)/.exec(h)||["","","",""];if(0==k[0].length&&0==l[0].length)break;b=Wh(0==k[1].length?0:parseInt(k[1],10),0==l[1].length?0:parseInt(l[1],10))||Wh(0==k[2].length,0==l[2].length)||Wh(k[2],l[2]);g=k[3];h=l[3]}while(0==b)}return 0<=b})},ti;
var ui=Bb.document;ti=ui&&ei?mi()||("CSS1Compat"==ui.compatMode?parseInt(ri,10):5):void 0;var vi;if(!(vi=!ii&&!ei)){var wi;if(wi=ei)wi=9<=Number(ti);vi=wi}vi||ii&&si("1.9.1");ei&&si("9");var qb=function(a,b){var c="";ei&&!xi(a)&&(c='<script>document.domain="'+document.domain+'";\x3c/script>'+c);var d="<!DOCTYPE html><html><head><script>var inDapIF=true;\x3c/script>"+c+"</head><body>"+b+"</body></html>";if(yi)a.srcdoc=d;else if(zi){var e=a.contentWindow.document;e.open("text/html","replace");e.write(d);e.close()}else Ai(a,d)},yi=ki&&"srcdoc"in document.createElement("iframe"),zi=ii||ki||ei&&si(11),Ai=function(a,b){ei&&si(7)&&!si(10)&&6>Bi()&&Ci(b)&&(b=Di(b));var c=function(){a.contentWindow.goog_content=
b;a.contentWindow.location.replace("javascript:window.goog_content")};ei&&!xi(a)?Ei(a,c):c()},Bi=function(){var a=navigator.userAgent.match(/Trident\/([0-9]+.[0-9]+)/);return a?parseFloat(a[1]):0},xi=function(a){try{var b;var c=a.contentWindow;try{var d;if(d=!!c&&null!=c.location.href)b:{try{ai(c.foo);d=!0;break b}catch(e){}d=!1}b=d}catch(e){b=!1}return b}catch(e){return!1}},Fi=0,Ei=function(a,b){var c="goog_rendering_callback"+Fi++;Bb[c]=b;a.src="javascript:'<script>(function() {document.domain = \""+
document.domain+'";var continuation = window.parent.'+c+";window.parent."+c+" = null;continuation();})()\x3c/script>'"},Ci=function(a){for(var b=0;b<a.length;++b)if(127<a.charCodeAt(b))return!0;return!1},Di=function(a){for(var b=unescape(encodeURIComponent(a)),c=Math.floor(b.length/2),d=[],e=0;e<c;++e)d[e]=String.fromCharCode(256*b.charCodeAt(2*e+1)+b.charCodeAt(2*e));1==b.length%2&&(d[c]=b.charAt(b.length-1));return d.join("")};/*
 Copyright (c) 2014 Derek Brans, MIT license https://github.com/krux/postscribe/blob/master/LICENSE. Portions derived from simplehtmlparser, which is licensed under the Apache License, Version 2.0 */

var Vi=function(a,b,c,d,e){var f=a+"{"+(b+": "+c+(d?" !important":""))+"}";e&&(f=e+"{"+f+"}");var g=document;if(g.createStyleSheet){var h=Si(g),k=h.rules.length;h.insertRule(f,k);return function(){h.deleteRule?h.deleteRule(k):h.removeRule(k);h.insertRule("x {}",k)}}var l=Ti(f,g);Ui(l,g);var m=l.parentNode;return function(){m.removeChild(l)}},Wi=null,Si=function(a){if(Wi)return Wi;for(var b=a.styleSheets.length-1;0<=b;b--){var c=a.styleSheets[b],d=c.ownerNode;if(d&&d.parentNode&&"HEAD"==d.parentNode.tagName)return Wi=
c}0==a.styleSheets.length&&a.createStyleSheet();return Wi=a.styleSheets[0]},Ti=function(a,b){var c=(b||document).createElement("style");void 0!==c.cssText?c.cssText=a:c.innerHTML=a;return c},Ui=function(a,b){var c=b||document,d=c.getElementsByTagName("head")[0];d||(d=c.createElement("head"),c.body.parentNode.insertBefore(d,c.body));d.appendChild(a)};var cj={},dj=void 0,ej=function(a){var b=cj[a];b||(b={id:a,v:[],ja:0,eb:null,Pa:void 0,Va:!1},cj[a]=b);dj=b},gj=function(a,b,c,d){var e=dj;if(!Vg||!e)return!1;var f={id:e.id+":"+e.v.length,Ob:b,ca:[],Jb:c,I:a,La:0,Fa:d||null,nb:0,ia:!1};e.v.push(f);null===a?(f.ia=!0,b(null)):fj(e);return!0},hj=function(a){var b=Vi(a,"visibility","hidden",!0);return function(){U(b)&&b.apply();b=null}},ij=function(a,b,c,d){var e=b;if(!jb){var f=hj(a.A);lb.push(f);e=function(a,c){var d=b(a,c);f();return d}}return gj(a,
e,c,d)},fj=function(a){if(!a.Va){for(var b=a.ja;b<a.v.length;b++){var c=a.v[b],d=b==a.ja;if(!c.ia&&!jj(d,c))break;c.ia&&d&&a.ja++}a.v.length>a.ja?(a.eb||(a.eb=B.setTimeout(function(){a.eb=null;fj(a)},80)),jb||a.Pa||(a.Pa=function(){u(function(){fj(a)})},S(R,"DOMContentLoaded",a.Pa))):kj(a)}},kj=function(a){for(var b=0;b<a.v.length;b++){var c=a.v[b];if(c.I)for(var d=ia(c.I.A)||[],e=0;e<d.length;e++){var f=d[e];f.gtmProgressiveApplied&&f.gtmProgressiveApplied[c.id]||(lj(f,c.id),c.ca.push(mj(f,c.id)))}}},
jj=function(a,b){var c=[];if(b.I){var d=nj(b.I,b.id),e=null;b.Fa&&(e=nj(b.Fa,b.id+"-t"));for(var f=0;f<d.length;f++){var g=d[f],h;if(null!=e&&(h=e.length>f?e[f]:null,!h&&!jb&&(null===b.Fa.s||b.nb+c.length<b.Fa.s)))break;c.push({element:g,Oc:h})}}if(!jb&&b.Jb&&(!a||null==b.I.s||b.I.s!=b.La+c.length))return!1;for(var k=0;k<c.length;k++){var l=c[k].element,m=c[k].Oc,n;b.La++;lj(l,b.id);m&&(b.nb++,n=b.id+"-t",lj(m,n));var q=b.Ob(l,m);U(q)&&b.ca.push(q);b.ca.push(mj(l,b.id));m&&n&&b.ca.push(mj(m,n))}if(b.I.s&&
b.I.s==b.La||jb)b.ia=!0;return!0},lj=function(a,b){a.gtmProgressiveApplied||(a.gtmProgressiveApplied={});a.gtmProgressiveApplied[b]=!0},mj=function(a,b){return function(){a.gtmProgressiveApplied&&delete a.gtmProgressiveApplied[b]}},nj=function(a,b){for(var c=ia(a.A)||[],d=[],e=0;e<c.length;e++){var f=c[e];if(!f.gtmProgressiveApplied||!f.gtmProgressiveApplied[b]){if(a.G&&!oj(f))break;d.push(f)}}return d},oj=function(a){if(jb)return!0;for(;a;){if(a.nextSibling)return!0;a=a.parentNode}return!1};var _cl=function(a,b){sa("CLICK");u(b)};_cl.a="cl";_cl.b=["google"];var Ga=function(a,b){var c=b||Bb,d=c.onerror,e=!1;ki&&!si("535.3")&&(e=!e);c.onerror=function(b,c,h,k,l){d&&d(b,c,h,k,l);a({message:b,fileName:c,line:h,gd:k,error:l});return e}};var Jj=function(a){if(!a)return!1;if(a[Tb]&&Qa(a[Vb])){for(var b=a[Vb],c=0;c<b.length;c++)if(a[Vb]=b[c],Of(a))return!0;return!1}return Of(a)};var fk=76,gk=[],hk=[],Cg=[],ik=new Nf,jk=[],kk=[],Sg=[],Tg=[],lk=function(){this.P=[]};lk.prototype.set=function(a,b){this.P.push([a,b]);return this};lk.prototype.resolve=function(a,b){for(var c={},d=0;d<this.P.length;d++){var e=Fg(this.P[d][0],a,b),f=Fg(this.P[d][1],a,b);c[e]=f}return c};var mk=function(a){this.index=a};mk.prototype.resolve=function(a,b){var c=Cg[this.index];if(c&&!b(c)){var d=c[Na];if(a){if(a.get(d))return;a.set(d,!0)}c=Fg(c,a,b);a&&a.set(d,!1);return Of(c)}};
var _M=function(a){return new mk(a)},nk=function(a){this.resolve=function(b,c){for(var d=[],e=!1,f=0;f<a.length;f++){var g=Fg(gk[a[f]],b,c);g===cb&&(e=!0);d.push(g)}return e?new mb(d):d.join("")}},_T=function(a){return new nk(arguments)},ok=function(a){function b(b){for(var c=1;c<a.length;c++)if(a[c]==b)return!0;return!1}this.resolve=
function(c,d){var e=Fg(a[0],c,d);if(a[0]instanceof mk&&b(8)&&b(16)){if(e===cb)return e;var f=xa();ik.set(f,e);return'google_tag_manager["GTM-NZHN7H"].macro(\''+f+"')"}e=String(e);for(var g=1;g<a.length;g++)e=Kj[a[g]](e);return e}},_E=function(a,b){return new ok(arguments)},pk=function(a,b){this.w=a;this.ra=b},_R=function(a,b){return new pk(a,b)};
var Fg=function(a,b,c){var d=a;if(a instanceof mk||a instanceof lk||a instanceof nk||a instanceof ok)return a.resolve(b,c);if(!(a instanceof pk))if(Qa(a)){d=[];for(var e=0;e<a.length;e++)d[e]=Fg(a[e],b,c)}else if(a&&"object"==typeof a){d={};for(var f in a)a.hasOwnProperty(f)&&(d[f]=Fg(a[f],b,c))}return d},sk=function(){for(var a=[_jsm,'platform','(function(){var a\x3dnavigator.userAgent;a:{for(var c\x3d[{platform:\x22Frodo\x22,pattern:/com.douban.frodo/i},{platform:\x22WeChat\x22,pattern:/MicroMessenger/i},{platform:\x22Weibo\x22,pattern:/Weibo/i},{platform:\x22QQ\x22,pattern:/ QQ/i}],b\x3d0,d\x3dc.length;b\x3cd;b++)if(c[b].pattern.test(a)){a\x3dc[b].platform;break a}a\x3d\x22Others\x22}return a})();',_T(2),'open-source','(function(){var a\x3dwindow.location.search;a:{for(var c\x3d[{source:\x22\\u670b\\u53cb\\u5708\x22,pattern:/timeline/i},{source:\x22\\u7fa4\\u804a\x22,pattern:/groupmessage/i},{source:\x22\\u79c1\\u804a\x22,pattern:/singlemessage/i}],b\x3d0,d\x3dc.length;b\x3cd;b++)if(c[b].pattern.test(a)){a\x3dc[b].source;break a}a\x3d\x22Others\x22}return a})();',_T(5),'share-source','(function(){var a\x3dwindow.location.search;a:{for(var c\x3d[{source:\x22\\u516c\\u4f17\\u53f7\x22,pattern:/weixin-feed/i},{source:\x22frodo\x22,pattern:/FeatureFeedTheme|dt_/i}],b\x3d0,d\x3dc.length;b\x3cd;b++)if(c[b].pattern.test(a)){a\x3dc[b].source;break a}a\x3d\x22Others\x22}return a})();',_T(8),_eq,__e,'_event','1',_M(3),'gtm.js','2413993_2147479553',__ua,true,false,'TRACK_PAGEVIEW','index','dimension',_M(0),{21:13,22:23},[24],'UA-53594431-4',4,'3',_M(1),{21:28,22:29},[30],9,_cn,_v,'Click Classes','gtm.elementClasses',_M(4),'promo_button download_app','gtm.click','点击','2413993_34','下载','TRACK_EVENT',11,_re,_u,'Page URL',_M(5),'/page','2413993_46','fieldName','value','sampleRate','4',{51:53,52:54},[55],'UA-53594431-3',12,'UA-53594431-6',13,14,'2413993_47',_cl,15,'Page Hostname','host','Page Path','path',_f,'Referrer','Event','Click Element','gtm.element','Click ID','gtm.elementId','Click Target','gtm.elementTarget','Click URL','gtm.elementUrl',_et,'Click Text'],b=[],c=0;c<a.length;c++)b[c]=
rk(c,a);return b},rk=function(a,b){var c=b[a],d=c;if(c instanceof mk||c instanceof ok||c instanceof nk||c instanceof pk)d=c;else if(Qa(c)){d=[];for(var e=0;e<c.length;e++)d[e]=rk(c[e],b)}else if("object"==typeof c){d=new lk;for(var f in c)c.hasOwnProperty(f)&&d.set(b[f],rk(c[f],b))}return d},uk=function(a,b){for(var c=b?b.split(","):[],d=0;d<c.length;d++){var e=c[d]=c[d].split(":");0==a&&(e[1]=
gk[e[1]]);if(1==a){var f=tk(e[0]);e=c[d]={};for(var g=0;g<f.length;g++){var h=hk[f[g]];e[h[0]]=h[1]}}if(2==a)for(g=0;4>g;g++)e[g]=tk(e[g]);3==a&&(c[d]=gk[e[0]]);if(4==a)for(g=0;2>g;g++)if(e[g]){e[g]=e[g].split(".");for(var k=0;k<e[g].length;k++)e[g][k]=gk[e[g][k]]}else e[g]=[];5==a&&(c[d]=e[0])}return c},tk=function(a){var b=[];if(!a)return b;for(var c=0,d=0;d<a.length&&c<fk;c+=6,d++){var e=a&&a.charCodeAt(d)||65;if(65!=e){var f;f=65<e&&90>=e?e-65:97<=e&&122>=e?e-97+26:95==e?63:48<=e?e-48+52:62;1&
f&&b.push(c);2&f&&b.push(c+1);4&f&&b.push(c+2);8&f&&b.push(c+3);16&f&&b.push(c+4);32&f&&b.push(c+5)}}return b},vk=function(a,b,c){a.push.apply(a,uk(b,c))};var wk;
var Eg=function(a,b){if(null===a||void 0===a)return a;if(b.propertyRenamingRequired){var c={},d;for(d in a)if(a.hasOwnProperty(d)){var e=zk[d];e&&0==e.indexOf("vtp_")&&(c[e]=a[d])}c.__metadata=b;return c}return a},Ck=function(a){},Dk=function(a,b){},Hg=function(a){};var Ek,Fk;
var Rk=function(a){return function(){}},Sk=function(a){return function(){}};var Tk=function(a){var b=this;this.h=a;this.fa=this.Eb=!1;this.Ea=[];this.Ba=[];this.Z=function(){b.fa||Sf(b.Ea);Vf(b,1);if(Ib[a])for(var c=0;c<Ib[a].length;c++)Ib[a].shift().Z()};this.Y=function(){b.fa||Sf(b.Ba);Vf(b,2);if(Ib[a])for(var c=0;c<Ib[a].length;c++)Ib[a].shift().Y()};this.C=ob},Uk=function(a,b){a.Ea.push(b)},Vk=function(a,b){a.Ba.push(b)},Wk=function(a){this.K=[];this.ab=[];this.pb={};this.wb=[];this.X=0;this.Za={};this.cb={};this.bb={};this.event=a};Wk.prototype.addListener=function(a){this.wb.push(a)};
var Xk=function(a){0<a.X||Sf(a.wb)},Yk=function(a,b,c,d,e,f){if(!c.fa){a.K[b]=c;void 0==d&&(d=[]);void 0==e&&(e=[]);void 0==f&&(f=[]);d=Qa(d)?d.slice():["or",d];e=Qa(e)?e.slice():[e];f=Qa(f)?f.slice():[f];a.pb[b]=d;a.Za[b]=0<e.length;a.cb[b]=0<f.length;a.X++;var g=function(){0<a.X&&!a.Za[b]&&!a.cb[b]&&a.X--;Xk(a)};Uk(c,g);Vk(c,g)}},cl=function(a){for(var b=[],c={},d=0;d<a.K.length;c={S:c.S},d++)if(c.S=a.K[d],c.S){var e=a.pb[d],f=a.Za[d],g=a.cb[d];if(0!=e.length||f||g){if(0<e.length)for(var h=Zk(e,
c.S.C),k=0;k<e.length;k++)e[k]instanceof pk&&e[k].w!=d&&$k(a,e[k].w,h);(f||g)&&al(a,d,function(a){return function(){0<a.S.B.X&&a.S.B.X--;Xk(a.S.B)}}(c))}else b.push(d)}for(d=0;d<b.length;d++)a.K[b[d]].C();for(d=0;d<a.ab.length;d++){var l=a.ab[d];bl(l);0<l.length&&l[0].C()}},$k=function(a,b,c){a.K[b]&&(Uk(a.K[b],function(){c(b,!0)}),Vk(a.K[b],function(){c(b,!1)}))},Zk=function(a,b){var c=ob,d=!1;return function(e,f){var g;a:{for(var h=0;h<a.length;h++)if(a[h]instanceof pk&&a[h].w===e||a[h]===e){g=
h;break a}g=-1}d||0>g||("or"==a[0]?f?(d=!0,b()):(a.splice(g,1),1==a.length&&(d=!0,c())):f?(a.splice(g,1),1==a.length&&(d=!0,b())):(d=!0,c()))}},al=function(a,b,c){var d=[],e=!1,f=function(b){var c,g,h=kk[b];if(a.event.f(h)){}else g=dl(h,b,a.event.f,a);if(c=g){var k=el(b,!0);0<k.length&&f(k[0].w);d.push(c);var l=el(b,!1);0<l.length&&f(l[0].w)}else e=
!0};f(b);if(!e){for(var g=0;g<d.length;g++){var h=d[g],k=el(h.h,!0);if(0<k.length){var l=d[g-1],m=fl(h);Uk(l,m);0==k[0].ra?Vk(l,m):Vk(l,c)}var n=el(h.h,!1);0<n.length&&(m=fl(d[g+1]),Uk(h,m),0==n[0].ra?Vk(h,m):Vk(h,c))}Uk(d[d.length-1],c);Vk(d[d.length-1],c);a.ab.push(d)}},el=function(a,b){var c=b?Ke:af,d=kk[a],e=void 0===d[c]?[]:d[c];return Qa(e)?e:[e]},fl=function(a){return function(){a.C()}},bl=function(a){for(var b=[],c=0;c<a.length;c++){var d=a[c],e=d.h,f=Hb[e],g=f.firingOption;if(0!=g&&(1==g&&
void 0!==d.B.bb[e]||2==g&&void 0!==f.state)&&(b.push(d),2==f.state&&c!=a.length-1)){var h=el(a[c+1].h,!0);if(0<h.length&&1==h[0].ra)for(++c;c<a.length;c++)b.push(a[c])}}var k=gl(b),l;for(l in k)if(k.hasOwnProperty(l)){for(var m=void 0,n=void 0,q=k[l],v=q[0],w=q[q.length-1],r,A=0;A<a.length;A++){var D=a[A];!m&&D.h==v&&0<A&&(m=a[A-1]);D.h==w&&A<a.length-1&&(n=a[A+1]);if(-1<tb(q,D.h))if(r=a.splice(A,1)[0],D.h==w)break;else A--}if(r){var x=Number(l),z=m,H=n;if(z){var P=z.Ea[0],E=z.Ba[0],C=z;C.Ea=[];C.Ba=
[];Uk(z,P);Vk(z,E)}if(z&&H){var F=fl(H);Uk(z,F);var J=el(z.h,!1);0<J.length&&J[0].w!=x&&0==J[0].ra&&Vk(z,F);var L=el(H.h,!0);0<L.length&&L[0].w!=x&&0==L[0].ra&&Vk(z,F)}}}},gl=function(a){for(var b={},c=0;c<a.length;c++){var d=a[c],e=[],f=function(a){var b=el(a,!0);0<b.length&&f(b[0].w);e.push(a);var c=el(a,!1);0<c.length&&f(c[0].w)};f(d.h);b[d.h]=e}hl(a,b);return b},hl=function(a,b){for(var c=0;c<a.length;c++){var d=a[c].h,e;for(e in b)if(b.hasOwnProperty(e)&&e!=d&&-1<tb(b[e],d)){delete b[d];break}}};var il=function(a,b,c){return function(){a[wd]=b.Z;a[xd]=b.Y;var d=b.h,e=b.B&&b.B.bb[d],f=Hb[d]&&Hb[d].state,g=e?void 0!==e:b.Eb||b.fa,h=Hb[d]&&Hb[d].firingOption,k=h&&2==h,l=h&&1==h;if(!g&&void 0===f||!g&&!k||!k&&!l){Vf(b,0);var m=b.B?b.B.event:void 0,n=a;n=Fg(n,new Nf,c);a=n;if(m){}Of(a,b.Z,b.Y)}else k&&0==f||l&&0==e?Ib[d].push(b):k&&1==f||l&&1==e?b.Z():b.Y()}},dl=function(a,b,c,d){var e=d&&d.K,f;if(f=e)a:{if(e&&Qa(e)&&0!=e.length)for(var g=0;g<e.length;g++)if(e[g]&&e[g].h===b){f=e[g];break a}f=void 0}var h=f||new Tk(b);h.B=d;Uk(h,Rk(a));Vk(h,Sk(a));h.C=il(a,h,c);return h};var nl=function(){var a=[];return function(b,c){if(void 0===a[b]){var d=jk[b]&&Fg(jk[b],new Nf,c),e=d;d&&(e=Jj(d));a[b]=[e,d]}return a[b]}},ol=function(a,b){for(var c=b[0],d=0;d<c.length;d++)if(!a.W(c[d],a.f)[0])return!1;var e=b[2];for(d=0;d<e.length;d++)if(a.W(e[d],a.f)[0])return!1;return!0},pl=!1;
wg=function(a,b,c,d,e){switch(b){case "gtm.js":if(pl)return!1;pl=!0;break;case "gtm.sync":if(Y("gtm.snippet")!=Fb)return!1}for(var f={id:a,name:b,wa:d||ob,Ka:tk(),Ua:tk(),W:nl(),f:Bg(c)},g=[],h=0;h<Sg.length;h++)if(ol(f,Sg[h])){g[h]=!0;for(var k=f,l=Sg[h],m=l[1],n=0;n<m.length;n++)k.Ka[m[n]]=!0;var q=l[3];for(n=0;n<q.length;n++)k.Ua[q[n]]=!0}else g[h]=!1;var L=[];for(var G=0;G<fk;G++)if(f.Ka[G]&&!f.Ua[G])if(f.f(kk[G])){}else{L[G]=kk[G];}f.oa=L;for(var M=new Wk(f),K=0;K<fk;K++)if(f.Ka[K]&&!f.Ua[K])if(f.f(kk[K])){}else{var N=f.oa[K],ua=dl(N,K,f.f,M);Yk(M,K,ua,N[Tc],N[Ke],N[af]);if(N[Jb])break}M.addListener(f.wa);cl(M);Xk(M);e&&U(e)&&e({passingRules:g,resolvedTags:f.oa});if("gtm.js"==b||"gtm.sync"==b)a:{}for(var Jf in f.oa)if(f.oa.hasOwnProperty(Jf)){var Kf=
f.oa[Jf],ud;if(!(ud=void 0==Kf[Na])){var Lf=Kf[Na];ud=!("function"!=typeof String.prototype.startsWith?0===Lf.indexOf("_implicit"):Lf.startsWith("_implicit"))}if(ud)return!0}return!1};var rl=function(){};var sl=function(){};var ql={macro:function(a){if(ik.contains(a))return ik.get(a)}};ql.dataLayer=kg;ql.onHtmlSuccess=Uh(!0);ql.onHtmlFailure=Uh(!1);ql.callback=function(a){La.hasOwnProperty(a)&&U(La[a])&&La[a]();delete La[a]};
ql.Vb=function(){var a=B.google_tag_manager;a||(a=B.google_tag_manager={});db=a;if(a["GTM-NZHN7H"]){var b=db.zones;b&&b.registerNatural("GTM-NZHN7H")}else{a["GTM-NZHN7H"]=ql;dh();Ug();gk.push.apply(gk,sk());vk(hk,0,"3:0,4:1,5:3,4:4,5:6,4:7,5:9,3:10,3:11,4:12,10:13,0:14,1:15,3:17,8:18,13:19,24:19,28:19,29:19,25:20,11:19,16:19,12:25,14:19,27:26,17:19,18:19,15:18,9:27,12:31,9:32,3:33,3:34,4:35,6:36,0:37,1:38,1:39,7:18,22:19,20:42,25:43,19:40,26:18,9:44,3:45,3:46,4:47,0:48,1:49,21:56,27:57,9:58,23:18,27:59,9:60,9:61,3:63,9:64,4:65,2:66,4:67,2:68,3:69,4:70,4:71,4:72,6:73,4:74,6:75,4:76,6:77,4:78,6:79,3:80,4:81");vk(Cg,1,"H,Z,hB,Ac,AAAAAc,AAAAAAAw,AAAAAAAQAgB,AAAAAAAQAAG,AAAAAAAAAAY,AUAAAAAAAAg,AAAAAEAAAAAD,AAAAAEAAAAAM,AAAAAEAAAAAw,AAAAAEAAAAAAD,AAAAAAAAAAAAM");vk(jk,1,"AiB,AAAAAiB,AiAAAAC,AAAAAAAID");vk(kk,1,"AQ-_f,AQ-vvB,AQ6oPA8H,AQ-vOAAAc,AQ6vOAEAkD,AQ-_OAAAAF,AAAAAAAAAY");vk(Sg,2,"B:jB::,G:E::,J:Y::");vk(Tg,4,"16.16.16.62:,41:,50.50:");for(var c=0;c<kk.length;c++){var d=
kk[c],e=1;d[he]?e=2:d[tf]&&(e=0);Hb[c]={firingOption:e,state:void 0};Ib[c]=[]}sg();Kg();var n=B;if("interactive"==R.readyState&&!R.createEventObject||"complete"==R.readyState)$f();else{S(R,"DOMContentLoaded",$f);S(R,"readystatechange",$f);if(R.createEventObject&&R.documentElement.doScroll){var q=!0;try{q=!n.frameElement}catch(A){}q&&bg()}S(n,"load",$f)}"complete"===R.readyState?eg():S(B,"load",eg);sl();rl();a:{}}};ql.Vb();var _vs="res_ts:1500869045141000,srv_cl:169273974,ds:live,cv:36";
})()
